# cookbook-java-service-k8s.yaml
# version: 240701 - Riverbed Community Toolkit
#
# Usage:
#
#   kubectl apply -f cookbook-java-service-k8s.yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: cookbook-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cookbook-app
  name: yourapp
  labels:
    app.kubernetes.io/name: yourapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: yourapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: yourapp
      ###############################################
      # Riverbed APM configuration
      annotations:
        instrument.apm.riverbed/inject-java: "true"
      ###############################################              
    spec:
      containers:
      - name: java-spring-yourapp
        image: springio/gs-spring-boot-docker
        resources:
          limits:
            cpu: 500m
            memory: 350Mi
          requests:
            cpu: 300m
            memory: 200Mi        
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: cookbook-app
  name: yourapp
spec:
  # Uncomment the following line to create a LoadBalancer service (if supported by your Kubernetes environment)
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: yourapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080