FROM ubuntu:24.04
LABEL org.opencontainers.image.authors="Riverbed Community"
LABEL org.opencontainers.image.source="https://github.com/riverbed/Riverbed-Community-Toolkit"

RUN apt-get update
RUN apt-get install --no-install-recommends -y python3 python3-pip ansible git
RUN apt-get autoremove && apt-get clean && apt-get autoclean && rm -rf /var/lib/apt/lists/*
    
RUN mkdir /etc/ansible
RUN echo "localhost" >> /etc/ansible/hosts
RUN pip install --break-system-packages mysql-connector-python

# Install SteelScript and modules (latest version)
# ref: https://github.com/riverbed/steelscript > Quickstart
RUN pip install --break-system-packages \
    git+https://github.com/riverbed/steelscript \
    git+https://github.com/riverbed/steelscript-appresponse \
    git+https://github.com/riverbed/steelscript-netprofiler 

# Create Ansible modules from the scripts inside modules subfolder 
COPY ./modules/*.py /usr/lib/python3/dist-packages/ansible/modules/riverbed/

WORKDIR /app

CMD ["sleep infinity"]
