# compose.yaml
#
# Riverbed-Community-Toolkit
# 101-apm-collector-with-docker-compose
# version: 25.3.29
#
# Compose file to deploy the Riverbed APM Collector on a docker host
#
# Usage
#
#   docker compose up
#
# Example in Bash
#   export RIVERBED_APM_SAAS_SERVER_HOST="agents.apm.myaccount.aternity.com"
#   export RIVERBED_APM_CUSTOMER_ID="12341234-12341234-13241234"
#   docker compose up
#
# Example in PowerShell
#   $env:RIVERBED_APM_SAAS_SERVER_HOST="agents.apm.myaccount.aternity.com"
#   $env:RIVERBED_APM_CUSTOMER_ID="12341234-12341234-13241234"
#   docker compose up

services:

  riverbed-apm-opentelemetry-collector:

    # APM OpenTelemetry Collector
    # https://hub.docker.com/r/aternity/apm-collector

    image: registry.hub.docker.com/aternity/apm-collector:2022.11.0-4

    container_name: riverbed-apm-opentelemetry-collector

    environment:
    
      SERVER_URL: "wss://${RIVERBED_APM_SAAS_SERVER_HOST}/?RPM_AGENT_CUSTOMER_ID=${RIVERBED_APM_CUSTOMER_ID}"
    
    ports:

      # Uncomment the telemetry protocol to expose the collector ports

      # OpenTelemetry, https://opentelemetry.io
      - "4317:4317/tcp"   # OpenTelemetry OTLP over gRPC
      - "4318:4318/tcp"     # OpenTelemetry OTLP JSON/Protobuf over HTTP
      # - "55681:55681/tcp" # OpenTelemetry OTLP JSON/Protobuf over HTTP
      
      # Jaeger, https://www.jaegertracing.io
      # - "14268:14268/tcp" # Jaeger Thrift Binary over HTTP
      # - "6831:6831/udp"   # Jaeger Thrift Compact
      # - "6832:6832/udp"   # Jaeger Thrift Binary
      
      # Zipkin, https://zipkin.io
      # - "9411:9411/tcp"   # Zipkin v2 json/protobuf and v1 json/thrift
      # - "5775:5775/udp"   # Jaeger's Thrift support for Zipkin v1
